# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2 
  displayName: 'Dot Net Core build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Pipelines-dotnet-core'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/pipelines-dotnet-core-tests/NUnitTestProject1-Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Pipeline Test Run'  
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Pipelines-dotnet-core'
    downloadPath: '$(System.ArtifactsDirectory)'
