# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2 
  displayName: 'Dot Net Core build'
  inputs:
    command: 'build'
    projects: '**/*.csproj' 

    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Output'
    
- task: PowerShell@2
  displayName: List Files Post Build
  inputs:
    filePath: $(Build.ArtifactStagingDirectory)/Output
    targetType: inline
    script: Get-ChildItem
    arguments: '-Recurse -Depth 4'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Output'
    ArtifactName: 'Pipelines-dotnet-core'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/pipelines-dotnet-core-tests/NUnitTestProject1-Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Pipeline Test Run'  
- task: DownloadBuildArtifacts@0
  inputs:
    buildVersionToDownload: latest
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Pipelines-dotnet-core'
    downloadPath: '$(System.ArtifactsDirectory)'
